language: java
jdk:
  - openjdk7
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository
# Just skip installation step
# cause everything is done
# in script step.
install: yes
script:
  - mvn -Prun-its clean verify
